Add configuration for docker and job scheduling
mozilla/etl-graph pull request #8
Opened 2021-01-21 23:37 UTC by acmiyaguchi

This adds docker configuration that will allow this image to be scheduled every day on airflow. My plan is to add this to [docker-etl](https://github.com/mozilla/docker-etl) as a submodule (kept up to date with dependabot), and then create a new DAG in telemetry-airflow.

2021-01-21 23:39 UTC, acmiyaguchi commented
@wlach I was wondering if you would be interested in reviewing this, otherwise I can shop around.

2021-01-22 15:52 UTC, wlach requested changes
I have a few thoughts on architecture from skimming the PR, let me know if I'm missing something.

2021-01-22 15:52 UTC, wlach commented on Dockerfile
> +CMD scripts/scrape.sh && scripts/deploy.sh
I think we should skip packaging/deploying the web assets as part of the docker container, as it makes builds slower and larger. Instead, I'd suggest the docker container *only* be responsible for scraping/updating the backend data and just upload any web assets as part of the CI process in this repository.

You can see an example of uploading to a protosaur GCS bucket from circleci here: https://github.com/mozilla/funnel/blob/main/.circleci/config.yml (I configured a secret to store the service account credentials)

2021-01-22 15:52 UTC, wlach commented on docker-compose.yml
> +version: "3.4"
I wonder if using docker-compose is the right choice here? Especially if the container is just going to scrape, I might just write up a small helper script to invoke the container to do that.

2021-01-22 17:00 UTC, acmiyaguchi commented on docker-compose.yml
> +version: "3.4"
I think it's definitely the right tool to use. It takes care of a bunch of small things that would be a pain to do in a script/Makefile manually like building the container, mounting credentials, application code, and reading from an environment file.

2021-01-22 17:13 UTC, acmiyaguchi commented on Dockerfile
> +CMD scripts/scrape.sh && scripts/deploy.sh
I'll think of a slightly better process for what exists now. It might end up being something along the lines of:

* deploy-data.sh (for airflow/docker-etl)
* deploy-site.sh (for ci)

2021-01-25 20:22 UTC, wlach approved these changes
I'm still not feeling like running the build inside the docker container is not the right approach, since it makes the end result much bigger than it need be, but I don't want to block landing this.

2021-01-25 20:22 UTC, wlach commented on Dockerfile
> +RUN npm run build
I would at least get rid of `node_modules/` and `.git` if you're going to do it this way.

```suggestion
RUN npm run build
RUN rm -rf node_modules/ .git
```

2021-01-25 20:53 UTC, acmiyaguchi commented on Dockerfile
> +RUN npm run build
`gcr.io/google.com/cloudsdktool/cloud-sdk` isn't a small image if we're worrying about size. In the Dockerfile, I was aiming toward optimizing for incremental build and run times. The image rebuilds the `node_modules` layer only when the `package.json` changes, so successive calls to `docker-compose up` to run the workflow already has dependencies installed.

We typically don't removed directories like `.git` and `site-packages` from our other dockerized applications, and it's sometimes useful to have around.

2021-01-25 22:43 UTC, merged